title: "chromono.space"
description: "Court's personal site"
baseurl: ""
url: "https://chromono.space"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: /journal/:year:month:day/
