title: "chromonospace"
description: "personal website & blog"
baseurl: ""
url: "https://chromono.space"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: /journal/:year:month:day/

exclude:
  - README.md
